main: com.quartzy.itemplugin.ItemPlugin
name: @name@
version: @version@
api-version: 1.16
description: Add custom items

commands:
  testcommand:
    description: Just for tesing
    aliases:
      - test
    usage: "Usage: /<command> lol"
  refresh:
    description: Reload parts of the item plugin
    usage: "Usage: /refresh <items|block|recipes|all>"